version: "3"
services:
  db:
    image: solutionsoft/time-machine-for-mssql:2017-latest
    restart: always
    environment:
      SA_PASSWORD:   "demo$ite"
      MSSQL_PID:     "Express"
      TM_LICHOST:    "192.168.20.40"
      TM_LICPORT:    "57777"
      TM_LICPASS:    "docker"
    ports:
      - "17800:7800"
      - "1433:1433"
    volumes:
      - "./tmdata:/tmdata"
      - "./mssql:/var/opt/mssql"
