version: "3"
services:
  db:
    image: solutionsoft/time-machine-for-mssql:latest
    restart: always
    environment:
      MSADMIN_USER:  "1000"
      MSADMIN_GROUP: "0"
      SA_PASSWORD:   "%HEPx6[[2rmuwh_D"
      TM_LICHOST: "192.168.20.112"
      TM_LICPORT: "57777"
      TM_LICPASS: "demo$ite"
    ports:
      - "17800:7800"
      - "1433:1433"
    volumes:
      - "./tmdata:/tmdata"
      - "./mssql:/var/opt/mssql"
